### ISSUE TITLE
多卡sft finetuning_type full需要多大显存？

### ISSUE THREAD

**Issue by weicheng59** [hiyouga/ChatGLM-Efficient-Tuning#121]
根据案例尝试在8*80G A100上做全量微调，batch size设置为1了也提示OOM。
官方的deepspeed方案也尝试了，不会OOM，但是loss一直为0无法开始训练。
不知道是不是什么参数没有设置正确的问题。

> accelerate launch src/train_sft.py \
    --model_name_or_path /home/asus/llm/models/chatglm-6b \
    --do_train \
    --preprocessing_num_workers 32 \
    --dataset tdx \
    --finetuning_type full \
    --output_dir ./output/ \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 2000 \
    --learning_rate 1e-5 \
    --num_train_epochs 2.0 \
    --plot_loss \
    --fp16

accelerate配置
> compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 8
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by hiyouga** [comment]
如果按照官方的 [deepspeed config](https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/deepspeed.json) 使用 deepspeed 对本项目进行全参数微调呢？

**Comment by hiyouga** [comment]
试试这个 config 呢？
```
compute_environment: LOCAL_MACHINE                                                                                                    
deepspeed_config:                                                                                                                     
  gradient_accumulation_steps: 8
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
