### ISSUE TITLE
可以提供一个可以参考的的accelerate config_file么...accelerate一直启动不起来

### ISSUE THREAD

**Issue by zhxiucui** [hiyouga/ChatGLM-Efficient-Tuning#160]

**Comment by hiyouga** [comment]
```yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 你的GPU数量
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
